### ISSUE TITLE
Crash when trying to access menu items

### ISSUE THREAD

**Issue by rnestler** [molzy/plugin.audio.kxmxpxtx.bandcamp#4]
While the bandcamp menu starts I can't enter any menu item.

The logs show the following:
```
2024-08-17 11:42:27.659 T:975     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.audio.kxmxpxtx.bandcamp/default.py", line 179, in <module>
                                                       main()
                                                     File "/var/lib/kodi/.kodi/addons/plugin.audio.kxmxpxtx.bandcamp/default.py", line 114, in main
                                                       build_genre_list()
                                                     File "/var/lib/kodi/.kodi/addons/plugin.audio.kxmxpxtx.bandcamp/default.py", line 51, in build_genre_list
                                                       genre_list = list_items.get_genre_items(cache.cacheFunction(bandcamp.get_genres))
                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 609, in cacheFunction
                                                       ret_val = funct(*args)
                                                                 ^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.audio.kxmxpxtx.bandcamp/resources/lib/bandcamp_api/bandcamp.py", line 114, in get_genres
                                                       return self._get_data_blob()['signup_params']['genres']
                                                              ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--

2024-08-17 11:42:27.923 T:973     error <general>: GetDirectory - Error getting plugin://plugin.audio.kxmxpxtx.bandcamp/?mode=list_discover
2024-08-17 11:42:27.970 T:522     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.kxmxpxtx.bandcamp/?mode=list_discover) failed
```

Adding a few log messages it shows that the URL returns a 403 response:
```
2024-08-17 11:57:36.809 T:1910     info <general>: url: https://bandcamp.com/rnstlr
2024-08-17 11:57:36.810 T:1910     info <general>: request: <Response [403]>
2024-08-17 11:57:36.810 T:1910     info <general>: request content: b'\n<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n<html>\n  <head>\n    <title>403 Forbidden</title>\n  </head>\n  <body>\n    <h1>Error 403 Forbidden</h1>\n    <p>Forbidden</p>\n    <h3>Error 54113</h3>\n    <p>Details: cache-fra-etou8220128-FRA 1723888657 722597740</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n'
```

**Comment by molzy** [comment]
I also had this 403 issue, and published a release `v0.5.1` that resolves it on my end using a different user agent. It should be in the Kodi repo now. Let me know if that resolves the issue for you as well.
